Fix win errors: - fatal error C1083: Cannot open source file: ' /DWIN32 /D_WINDOWS /W3': No such file or directory [~\genfiles.vcxproj]   - removed quotes from line 17; set as a list and strip leading spaces - fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory [~\genfiles.vcxproj]   - added line 51; includes was set but not used in execute_process